### ISSUE TITLE
NameError: name 'target' is not defined

### ISSUE THREAD

**Issue by GooLey1025** [simon19891216/CentIER#13]
```Done.FASTA-Reader: Ignoring invalid residues at position(s): On line 4662: 1-1244
FASTA-Reader: Ignoring invalid residues at position(s): On line 6848: 1-4084

Traceback (most recent call last):
  File "/public/home/cszx_huangxh/qiujie/collabrators/gulei/results/CenTIER/Zlat/CentIERv3.0.py", line 684, in <module>
    else:print(target,'It appears that some errors occurred during the analysis of LTRs.You can contact the author to assist in resolving the issue.')
NameError: name 'target' is not defined
```
Does this two error have interaction with each other ?  
For the first error , the program did not end , it might be a warning.
For the second error, it tell me to contact author ,so i am here . I have run the ColCEN.data to exam , it goes well . 
Thanks for author's work . I would appreciate it for your any reply.

**Comment by simon19891216** [comment]
the version has been updated. please using the new version and try again, thank you



At 2024-08-24 14:32:48, "GooLey1025" ***@***.***> wrote:

FASTA-Reader: Ignoring invalid residues at position(s): On line 6848: 1-4084

Traceback (most recent call last):
  File "/public/home/cszx_huangxh/qiujie/collabrators/gulei/results/CenTIER/Zlat/CentIERv3.0.py", line 684, in <module>
    else:print(target,'It appears that some errors occurred during the analysis of LTRs.You can contact the author to assist in resolving the issue.')
NameError: name 'target' is not defined


Does this two error have interaction with each other ?
For the first error , the program did not end , it might be a warning.
For the second error, it tell me to contact author ,so i am here . I have run the ColCEN.data to exam , it goes well .
Thanks for author's work . I would appreciate it for your any reply.
