### ISSUE TITLE
New error when using the updated version of CentIER when using gff3 and Hi-C

### ISSUE THREAD

**Issue by biomichal** [simon19891216/CentIER#19]
The error message is:
```
Loading sequence file...
Allocating Memory...
Initializing data structures...
Computing TR Model Statistics...
Scanning Sequence 5...Traceback (most recent call last):
  File "/data/CentIER-main/centIER.py", line 675, in <module>
    hic_dir=merge_regions(hic_dir)
  File "/data/CentIER-main/centIER.py", line 125, in merge_regions
    if (n<m1 or m>n1)==False and index<length-2:target_list=[min(m,n,m1,n1),max(m,n,m1,n1)]
TypeError: '>' not supported between instances of 'int' and 'NoneType'
```

The command is: 
`centIER.py -o output --gff genome.gff3 --mul_cents --matrix1 hic_100000.matrix --matrix2 hic_20000.matrix --bed1 hic_100000_abs.bed --bed2 hic_20000_abs.bed genome.fas > run.log 2>run.err.log`

The log files:
[run.err.log](https://github.com/user-attachments/files/16808408/run.err.log)
[run.log](https://github.com/user-attachments/files/16808410/run.log)

**Comment by simon19891216** [comment]
Please contact me directly via email to obtain your data for troubleshooting purposes.



At 2024-08-30 07:48:24, "Meng Yang" ***@***.***> wrote:

The error message is:

Loading sequence file...
Allocating Memory...
Initializing data structures...
Computing TR Model Statistics...
Scanning Sequence 5...Traceback (most recent call last):
  File "/data/CentIER-main/centIER.py", line 675, in <module>
    hic_dir=merge_regions(hic_dir)
  File "/data/CentIER-main/centIER.py", line 125, in merge_regions
    if (n<m1 or m>n1)==False and index<length-2:target_list=[min(m,n,m1,n1),max(m,n,m1,n1)]
TypeError: '>' not supported between instances of 'int' and 'NoneType'


The command is:
centIER.py -o output --gff genome.gff3 --mul_cents --matrix1 hic_100000.matrix --matrix2 hic_20000.matrix --bed1 hic_100000_abs.bed --bed2 hic_20000_abs.bed genome.fas > run.log 2>run.err.log

The log files:
run.err.log
run.log

**Comment by mahnaz65** [comment]
Hi @biomichal,
I am hitting the same error with my own GFF, BED, and Hi-C matrix files (created using HiC-Pro).
Were you able to find a fix?

If you solved it, could you share how you fixed it.
Thank you very much for your help.

**Comment by simon19891216** [comment]
There seem to be significant format discrepancies in the Hi-C data, which may lead to errors. It is recommended to start with the genome and GFF files to give it a try.



At 2025-06-02 19:04:15, "mahnaz65" ***@***.***> wrote:

mahnaz65 left a comment (simon19891216/CentIER#19)

Hi @biomichal,
I am hitting the same error with my own GFF, BED, and Hi-C matrix files (created using HiC-Pro).
Were you able to find a fix?

If you solved it, could you share how you fixed it.
Thank you very much for your help.
