### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by mixle18** [simon19891216/CentIER#2]
Hi, I was trying your tool on the safflower data, i got this error. i have no clue how to solve this error.

LTR search has been completed, now start searching for the centromere region
Traceback (most recent call last):
  File "/media/safflower2/Data/megha/validation/CentIERv2.0/CentIERv2.0.py", line 576, in <module>
    p=identify_period_second(lists,f_period)
  File "/media/safflower2/Data/megha/validation/CentIERv2.0/CentIERv2.0.py", line 176, in identify_period_second
    target_cop=all_copy[0]
IndexError: list index out of range

similar error is showing with the test data.

**Comment by simon19891216** [comment]
We've conducted rigorous testing on CentIER and it performs well without issues when using test data. Can you please share your command line with me?



At 2024-03-05 17:58:44, "Megha Sharma" ***@***.***> wrote:

Hi, I was trying your tool on the safflower data, i got this error. i have no clue how to solve this error.

LTR search has been completed, now start searching for the centromere region
Traceback (most recent call last):
File "/media/safflower2/Data/megha/validation/CentIERv2.0/CentIERv2.0.py", line 576, in
p=identify_period_second(lists,f_period)
File "/media/safflower2/Data/megha/validation/CentIERv2.0/CentIERv2.0.py", line 176, in identify_period_second
target_cop=all_copy[0]
IndexError: list index out of range

similar error is showing with the test data.
