### ISSUE TITLE
Genome.gff  "Single positional indexer is out-of-bounds"

### ISSUE THREAD

**Issue by ErickTong** [simon19891216/CentIER#21]
Dear simon, 
   I hope this message finds you well. I am currently using the CentIER software for analyzing genome data, and I encountered an error while running the following command: 
```
 /data/Erick_Tong/software/CentIER/centIER.py --gff genome.gff \
                                              --matrix1 data_150000.matrix \
                                              --matrix2 data_20000.matrix \
                                              --bed1 data_150000_abs.bed \
                                              --bed2 data_20000_abs.bed \
                                              genome.fa
```
The error traceback is as follows: 
 ```
Traceback (most recent call last):
  File "/data/Erick_Tong/software/CentIER/centIER.py", line 674, in <module>
    hic_dir = findPosition(gap, finer_diag, bed1, bed2)
  File "/data/Erick_Tong/software/CentIER/centIER.py", line 235, in findPosition
    Rstart = int(bed2[(bed2["chr"] == chr) & (bed2["start"]==end)]["id"].iloc[0])
IndexError: single positional indexer is out-of-bounds
```
   This error seems to occur in the findPosition function when trying to access an element in bed2 based on the filtering condition. I would like to know if there are any specific formatting requirements for the genome.gff file or any of the input files that I might have overlooked. Additionally, could you provide any guidance on how to troubleshoot this issue effectively? Thank you for your assistance. I appreciate your work on this software! 
Best regards

**Comment by Allinonelearning** [comment]
hello, I meet the same situation, how did you solve it

**Comment by simon19891216** [comment]
I feel like this issue is more likely due to a problem with the input file itself. It's recommended to check the contents of the GFF file carefully.



At 2025-07-08 14:46:07, "Allinone" ***@***.***> wrote:

Allinonelearning left a comment (simon19891216/CentIER#21)

hello, I meet the same situation, how did you solve it

**Comment by Allinonelearning** [comment]
I only used the hic data, and this problem also occurred.

**Comment by simon19891216** [comment]
remove hic and try again



At 2025-07-10 18:04:20, "Allinone" ***@***.***> wrote:

Allinonelearning left a comment (simon19891216/CentIER#21)

I only used the hic data, and this problem also occurred.
