### ISSUE TITLE
centier

### ISSUE THREAD

**Issue by yao-chenxin** [simon19891216/CentIER#24]
hello.
I made the following mistake when I was running the centromere comment, hard to help see where the problem is, is the python problem or the software is not installed? I have a total of 28 genomes, but only two have this condition;

Initializing data structures...
Computing TR Model Statistics...
Scanning Sequence 585...
Freeing Memory...
Resolving output...
Done.Traceback (most recent call last):
  File "/T6/NA/00.USER/xxxxx/script/software/CenTIER/CentIER/centIER.py", line 781, in <module>
    max_number=max(number_list[i])
               ^^^^^^^^^^^^^^^^^^^
ValueError: max() iterable argument is empty

Look forward to your reply very much, thank you!

**Comment by simon19891216** [comment]
ok, you are welcome. Could you contact me by email ***@***.***)? I want to check the two genome file, because other genomes can be successfully analyzed.



At 2024-11-01 17:36:57, "yao" ***@***.***> wrote:

hello.
I made the following mistake when I was running the centromere comment, hard to help see where the problem is, is the python problem or the software is not installed? I have a total of 28 genomes, but only two have this condition;

Initializing data structures...
Computing TR Model Statistics...
Scanning Sequence 585...
Freeing Memory...
Resolving output...
Done.Traceback (most recent call last):
File "/T6/NA/00.USER/xxxxx/script/software/CenTIER/CentIER/centIER.py", line 781, in
max_number=max(number_list[i])
^^^^^^^^^^^^^^^^^^^
ValueError: max() iterable argument is empty

Look forward to your reply very much, thank you!

**Comment by yao-chenxin** [comment]
hello. 

According to your suggestion, I checked my genome file and found that there were contig sequences in it. I removed contig sequences that only contained chromosome level, and finally completed it successfully. 

Thank you very much for your reminding !




Good luck to you~










At 2024-11-03 18:36:55, "simon19891216" ***@***.***> wrote:

ok, you are welcome. Could you contact me by email ***@***.***)? I want to check the two genome file, because other genomes can be successfully analyzed.<br> <br> <br> <br> At 2024-11-01 17:36:57, &quot;yao&quot; ***@***.***&gt; wrote:<br> <br> hello.<br> I made the following mistake when I was running the centromere comment, hard to help see where the problem is, is the python problem or the software is not installed? I have a total of 28 genomes, but only two have this condition;<br> <br> Initializing data structures...<br> Computing TR Model Statistics...<br> Scanning Sequence 585...<br> Freeing Memory...<br> Resolving output...<br> Done.Traceback (most recent call last):<br> File &quot;/T6/NA/00.USER/xxxxx/script/software/CenTIER/CentIER/centIER.py&quot;, line 781, in<br> max_number=max(number_list[i])<br> ^^^^^^^^^^^^^^^^^^^<br> ValueError: max() iterable argument is empty<br> <br> Look forward to your reply very much, thank you!<br> <br> —<br> Reply to this email directly, view it on GitHub, or unsubscribe.<br> You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

**Comment by simon19891216** [comment]
ok, you are welcome
















At 2024-11-08 15:02:20, "yao" ***@***.***> wrote:

hello. <br> <br> According to your suggestion, I checked my genome file and found that there were contig sequences in it. I removed contig sequences that only contained chromosome level, and finally completed it successfully. <br> <br> Thank you very much for your reminding !<br> <br> <br> <br> <br> Good luck to you~<br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> At 2024-11-03 18:36:55, &quot;simon19891216&quot; ***@***.***&gt; wrote:<br> <br> ok, you are welcome. Could you contact me by email ***@***.***)? I want to check the two genome file, because other genomes can be successfully analyzed.&lt;br&gt; &lt;br&gt; &lt;br&gt; &lt;br&gt; At 2024-11-01 17:36:57, &amp;quot;yao&amp;quot; ***@***.***&amp;gt; wrote:&lt;br&gt; &lt;br&gt; hello.&lt;br&gt; I made the following mistake when I was running the centromere comment, hard to help see where the problem is, is the python problem or the software is not installed? I have a total of 28 genomes, but only two have this condition;&lt;br&gt; &lt;br&gt; Initializing data structures...&lt;br&gt; Computing TR Model Statistics...&lt;br&gt; Scanning Sequence 585...&lt;br&gt; Freeing Memory...&lt;br&gt; Resolving output...&lt;br&gt; Done.Traceback (most recent call last):&lt;br&gt; File &amp;quot;/T6/NA/00.USER/xxxxx/script/software/CenTIER/CentIER/centIER.py&amp;quot;, line 781, in&lt;br&gt; max_number=max(number_list[i])&lt;br&gt; ^^^^^^^^^^^^^^^^^^^&lt;br&gt; ValueError: max() iterable argument is empty&lt;br&gt; &lt;br&gt; Look forward to your reply very much, thank you!&lt;br&gt; &lt;br&gt; —&lt;br&gt; Reply to this email directly, view it on GitHub, or unsubscribe.&lt;br&gt; You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&amp;gt;<br> <br> —<br> Reply to this email directly, view it on GitHub, or unsubscribe.<br> You are receiving this because you authored the thread.Message ID: ***@***.***&gt;
