### ISSUE TITLE
Some errors

### ISSUE THREAD

**Issue by wjq1981** [simon19891216/CentIER#5]
When I use '-gff' the error is reported as follows：
 File "/dev/hdd/soft/CentIERv3.0/CentIERv3.0.py", line 639, in <module>
    if gff:gff_gene_number=ex_gff(gff)
                           ^^^^^^^^^^^
  File "/dev/hdd/soft/CentIERv3.0/CentIERv3.0.py", line 141, in ex_gff
    gff_gene_number[j]={}
    ^^^^^^^^^^^^^^^
NameError: name 'gff_gene_number' is not defined

When I don't use '-gff' I get the following error, but the result is produced：
File "/dev/hdd/soft/CentIERv3.0/CentIERv3.0.py", line 1078, in <module>
    else:s1,e1,seq1=st_range[ID]
NameError: name 'st_range' is not defined

Based on the code that had results produced, I added '-matrix1/2' and '-bed1/2' but again reported the following error:
Traceback (most recent call last):
  File "/dev/hdd/soft/CentIERv3.0/CentIERv3.0.py", line 647, in <module>
    hic_dir = findPosition(gap, finer_diag, bed1, bed2)#hic_dir是收集hic信号的
  File "/dev/hdd/soft/CentIERv3.0/CentIERv3.0.py", line 222, in findPosition
    Lstart = int(bed2[(bed2["chr"] == chr) & (bed2["start"]==start)]["id"].iloc[0])
  File "/home/anaconda3/envs/EDTA2/lib/python3.9/site-packages/pandas/core/indexing.py", line 879, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "/home/anaconda3/envs/EDTA2/lib/python3.9/site-packages/pandas/core/indexing.py", line 1496, in _getitem_axis
    self._validate_integer(key, axis)
  File "/home/anaconda3/envs/EDTA2/lib/python3.9/site-packages/pandas/core/indexing.py", line 1437, in _validate_integer
    raise IndexError("single positional indexer is out-of-bounds")
IndexError: single positional indexer is out-of-bounds

**Comment by simon19891216** [comment]
Ok, I will check the code in a few days. Please ensure that the required tools and computer environment are correctly installed

在 2024-08-15 11:57:16，"jinqiu wang" ***@***.***> 写道：


When I use '-gff' the error is reported as follows：
File "/dev/hdd/soft/CentIERv3.0/CentIERv3.0.py", line 639, in
if gff:gff_gene_number=ex_gff(gff)
^^^^^^^^^^^
File "/dev/hdd/soft/CentIERv3.0/CentIERv3.0.py", line 141, in ex_gff
gff_gene_number[j]={}
^^^^^^^^^^^^^^^
NameError: name 'gff_gene_number' is not defined

When I don't use '-gff' I get the following error, but the result is produced：
File "/dev/hdd/soft/CentIERv3.0/CentIERv3.0.py", line 1078, in
else:s1,e1,seq1=st_range[ID]
NameError: name 'st_range' is not defined

Based on the code that had results produced, I added '-matrix1/2' and '-bed1/2' but again reported the following error:
Traceback (most recent call last):
File "/dev/hdd/soft/CentIERv3.0/CentIERv3.0.py", line 647, in
hic_dir = findPosition(gap, finer_diag, bed1, bed2)#hic_dir是收集hic信号的
File "/dev/hdd/soft/CentIERv3.0/CentIERv3.0.py", line 222, in findPosition
Lstart = int(bed2[(bed2["chr"] == chr) & (bed2["start"]==start)]["id"].iloc[0])
File "/home/anaconda3/envs/EDTA2/lib/python3.9/site-packages/pandas/core/indexing.py", line 879, in getitem
return self._getitem_axis(maybe_callable, axis=axis)
File "/home/anaconda3/envs/EDTA2/lib/python3.9/site-packages/pandas/core/indexing.py", line 1496, in _getitem_axis
self._validate_integer(key, axis)
File "/home/anaconda3/envs/EDTA2/lib/python3.9/site-packages/pandas/core/indexing.py", line 1437, in _validate_integer
raise IndexError("single positional indexer is out-of-bounds")
IndexError: single positional indexer is out-of-bounds
