### ISSUE TITLE
Error reported when adding gff file option

### ISSUE THREAD

**Issue by jwli-code** [simon19891216/CentIER#6]
Not sure if it is a software problem or if my gff format does not meet the requirements of the software. It is recommended that authors provide an example-gff file that can be run.
```
Scanning Sequence 7...Traceback (most recent call last):
  File "CentIERv3.0.py", line 639, in <module>
    if gff:gff_gene_number=ex_gff(gff)
  File "CentIERv3.0.py", line 141, in ex_gff
    gff_gene_number[j]={}
NameError: name 'gff_gene_number' is not defined

```

**Comment by simon19891216** [comment]
Ok,I will solve it as soon as possible

在 2024-08-16 18:16:06，jwli ***@***.***> 写道：


Not sure if it is a software problem or if my gff format does not meet the requirements of the software. It is recommended that authors provide an example-gff file that can be run.

Scanning Sequence 7...Traceback (most recent call last):
  File "CentIERv3.0.py", line 639, in <module>
    if gff:gff_gene_number=ex_gff(gff)
  File "CentIERv3.0.py", line 141, in ex_gff
    gff_gene_number[j]={}
NameError: name 'gff_gene_number' is not defined

**Comment by jwli-code** [comment]
And is there a way or parameter to add threads to reduce the long runtime in genomic analysis?
