### ISSUE TITLE
NameError: name 'target' is not defined

### ISSUE THREAD

**Issue by biomichal** [simon19891216/CentIER#7]
Done.Traceback (most recent call last):
  File "/data/01_package/CentIERv3.0/CentIERv3.0.py", line 684, in <module>
    else:print(target,'It appears that some errors occurred during the analysis of LTRs.You can contact the author to assist in resolving the issue.')
NameError: name 'target' is not defined

**Comment by biomichal** [comment]
The above error message was from the following command using the example Arabidopsis data.
python CentIERv3.0.py -g ColCEN.fasta -mul_cents > Ath.log 2> Ath.err.log

Hope to solve it.

**Comment by jwli-code** [comment]
I also encountered the same problem, both gt and LTR_retrever can be called, and the final result is output, but this error will be reported.

**Comment by biomichal** [comment]
> If there are errors when running the example files, it indicates that there are issues with the installation environment of CentIER. Please verify if both gt and LTR_retriever are installed, and ensure that these two software can be directly called. At 2024-08-18 08:37:20, "Meng Yang" ***@***.***> wrote: The above error message was from the following command using the example Arabidopsis data. python CentIERv3.0.py -g ColCEN.fasta -mul_cents > Ath.log 2> Ath.err.log Hope to solve it. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

I have verified the environment path for both gt and LTR_retriver, including the versions  with CentIER package. 
![2024-08-20_164438](https://github.com/user-attachments/assets/9b855456-bc11-4b12-8019-a80c8c94d0de)
![2024-08-20_165444](https://github.com/user-attachments/assets/cdd45d95-9406-4373-8952-39d520500d7f)

**Comment by biomichal** [comment]
> If there are errors when running the example files, it indicates that there are issues with the installation environment of CentIER. Please verify if both gt and LTR_retriever are installed, and ensure that these two software can be directly called. At 2024-08-18 08:37:20, "Meng Yang" ***@***.***> wrote: The above error message was from the following command using the example Arabidopsis data. python CentIERv3.0.py -g ColCEN.fasta -mul_cents > Ath.log 2> Ath.err.log Hope to solve it. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

Here includes both of the two log files for "python CentIERv3.0.py -g ColCEN.fasta -mul_cents > Ath.log 2> Ath.err.log"
[Ath.err.log](https://github.com/user-attachments/files/16672665/Ath.err.log)
[Ath.log](https://github.com/user-attachments/files/16672666/Ath.log)

**Comment by simon19891216** [comment]
python CentIERv3.0.py -g ColCEN.fasta using this command and try again



At 2024-08-20 17:04:45, "Meng Yang" ***@***.***> wrote:

If there are errors when running the example files, it indicates that there are issues with the installation environment of CentIER. Please verify if both gt and LTR_retriever are installed, and ensure that these two software can be directly called. At 2024-08-18 08:37:20, "Meng Yang" @.> wrote: The above error message was from the following command using the example Arabidopsis data. python CentIERv3.0.py -g ColCEN.fasta -mul_cents > Ath.log 2> Ath.err.log Hope to solve it. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: @.>

Here includes both of the two log files for "python CentIERv3.0.py -g ColCEN.fasta -mul_cents > Ath.log 2> Ath.err.log"
Ath.err.log
Ath.log

**Comment by GooLey1025** [comment]
Traceback (most recent call last):
  File "./centIER.py", line 1080, in <module>
    else:s1,e1,seq1=st_range[ID]
NameError: name 'st_range' is not defined. Did you mean: 'seq_range'?

Hi, I have encountered the same problem , I would appreciate it for your any reply

**Comment by biomichal** [comment]
> python CentIERv3.0.py -g ColCEN.fasta using this command and try again At 2024-08-20 17:04:45, "Meng Yang" ***@***.***> wrote: If there are errors when running the example files, it indicates that there are issues with the installation environment of CentIER. Please verify if both gt and LTR_retriever are installed, and ensure that these two software can be directly called. At 2024-08-18 08:37:20, "Meng Yang" @.> wrote: The above error message was from the following command using the example Arabidopsis data. python CentIERv3.0.py -g ColCEN.fasta -mul_cents > Ath.log 2> Ath.err.log Hope to solve it. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: @.> Here includes both of the two log files for "python CentIERv3.0.py -g ColCEN.fasta -mul_cents > Ath.log 2> Ath.err.log" Ath.err.log Ath.log — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>

Yes, It works if without -mul_cents parameter. I think the software has still some potential bugs, for example using the -mul_cents parameter, or when using the GFF3 file. Hope to update in future.

**Comment by GooLey1025** [comment]
> > python CentIERv3.0.py -g ColCEN.fasta using this command and try again At 2024-08-20 17:04:45, "Meng Yang" _**@**_._**> wrote: If there are errors when running the example files, it indicates that there are issues with the installation environment of CentIER. Please verify if both gt and LTR_retriever are installed, and ensure that these two software can be directly called. At 2024-08-18 08:37:20, "Meng Yang" @.> wrote: The above error message was from the following command using the example Arabidopsis data. python CentIERv3.0.py -g ColCEN.fasta -mul_cents > Ath.log 2> Ath.err.log Hope to solve it. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: @.> Here includes both of the two log files for "python CentIERv3.0.py -g ColCEN.fasta -mul_cents > Ath.log 2> Ath.err.log" Ath.err.log Ath.log — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: _**@**_.**_>
> 
> Yes, It works if without -mul_cents parameter. I think the software has still some potential bugs, for example using the -mul_cents parameter, or when using the GFF3 file. Hope to update in future.

hello , how to work without -mul_cents parameter . My command line is python centIER.py x.fasta  , just so simple . This works with one reference genome.fasta , but when I run it with my own fasta , it will meet this problem . Does it have too much limit to the input fasta seq ?

**Comment by simon19891216** [comment]
This bug does not affect the prediction of centromere range. In addition, the bug has been fixed. Please download the new version and try again.



At 2024-08-29 17:42:27, "GooLey1025" ***@***.***> wrote:

Traceback (most recent call last):
File "./centIER.py", line 1080, in
else:s1,e1,seq1=st_range[ID]
NameError: name 'st_range' is not defined. Did you mean: 'seq_range'?

Hi, I have encountered the same problem , I would appreciate it for your any reply

**Comment by simon19891216** [comment]
the version havs been updated



At 2024-08-29 23:38:57, "Meng Yang" ***@***.***> wrote:

python CentIERv3.0.py -g ColCEN.fasta using this command and try again At 2024-08-20 17:04:45, "Meng Yang" @.> wrote: If there are errors when running the example files, it indicates that there are issues with the installation environment of CentIER. Please verify if both gt and LTR_retriever are installed, and ensure that these two software can be directly called. At 2024-08-18 08:37:20, "Meng Yang" @.> wrote: The above error message was from the following command using the example Arabidopsis data. python CentIERv3.0.py -g ColCEN.fasta -mul_cents > Ath.log 2> Ath.err.log Hope to solve it. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: @.> Here includes both of the two log files for "python CentIERv3.0.py -g ColCEN.fasta -mul_cents > Ath.log 2> Ath.err.log" Ath.err.log Ath.log — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.>

Yes, It works if without -mul_cents parameter. I think the software has still some potential bugs, for example using the -mul_cents parameter, or when using the GFF3 file. Hope to update in future.

**Comment by simon19891216** [comment]
I recommend you to contact me by email.



At 2024-08-30 00:16:22, "GooLey1025" ***@***.***> wrote:

python CentIERv3.0.py -g ColCEN.fasta using this command and try again At 2024-08-20 17:04:45, "Meng Yang" @.> wrote: If there are errors when running the example files, it indicates that there are issues with the installation environment of CentIER. Please verify if both gt and LTR_retriever are installed, and ensure that these two software can be directly called. At 2024-08-18 08:37:20, "Meng Yang" @.> wrote: The above error message was from the following command using the example Arabidopsis data. python CentIERv3.0.py -g ColCEN.fasta -mul_cents > Ath.log 2> Ath.err.log Hope to solve it. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: @.> Here includes both of the two log files for "python CentIERv3.0.py -g ColCEN.fasta -mul_cents > Ath.log 2> Ath.err.log" Ath.err.log Ath.log — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: _@**.**_>

Yes, It works if without -mul_cents parameter. I think the software has still some potential bugs, for example using the -mul_cents parameter, or when using the GFF3 file. Hope to update in future.

hello , how to work without -mul_cents parameter . My command line is python centIER.py x.fasta , just so simple . This works with one reference genome.fasta , but when I run it with my own fasta , it will meet this problem . Does it have too much limit to the input fasta seq ?

**Comment by GooLey1025** [comment]
****************************** Start defining the centromere range... *************************
****************************** Centromere range determination completed *************************
****************************** Annotating the centromere *************************
Traceback (most recent call last):
&nbsp; File "/public/home/cszx_huangxh/qiujie/collabrators/gulei/cen_analysis/results/Zlat_genome/./centIER.py", line 1081, in <module&gt;
&nbsp;&nbsp;&nbsp; else:s1,e1,seq1=st_range[ID]
ValueError: not enough values to unpack (expected 3, got 0)


你好！非常感谢您对CentIER软件的开发！

&nbsp; 这是我用更新的代码后运行的结果，仍然有报错。有可能是我的数据问题吗，因为example data 是没有问题的，我用了日本晴NIP基因组来运行也没有问题，但是换了个基因组fasta使用，就发生了这样的报错，谢谢你的回答！


她抱着明月
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "simon19891216/CentIER"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年8月30日(星期五) 中午1:58
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [simon19891216/CentIER] NameError: name 'st_range' is not defined (Issue #7)





 This bug does not affect the prediction of centromere range. In addition, the bug has been fixed. Please download the new version and try again.
 
 
 
 At 2024-08-29 17:42:27, "GooLey1025" ***@***.***&gt; wrote:
 
 Traceback (most recent call last):
 File "./centIER.py", line 1080, in
 else:s1,e1,seq1=st_range[ID]
 NameError: name 'st_range' is not defined. Did you mean: 'seq_range'?
 
 Hi, I have encountered the same problem , I would appreciate it for your any reply

**Comment by simon19891216** [comment]
***@***.***）联系，我需要看一下您的数据
















At 2024-09-02 14:14:16, "GooLey1025" ***@***.***> wrote:

****************************** Start defining the centromere range... *************************
****************************** Centromere range determination completed *************************
****************************** Annotating the centromere *************************
Traceback (most recent call last):
&nbsp; File "/public/home/cszx_huangxh/qiujie/collabrators/gulei/cen_analysis/results/Zlat_genome/./centIER.py", line 1081, in <module&gt;
&nbsp;&nbsp;&nbsp; else:s1,e1,seq1=st_range[ID]
ValueError: not enough values to unpack (expected 3, got 0)


你好！非常感谢您对CentIER软件的开发！

&nbsp; 这是我用更新的代码后运行的结果，仍然有报错。有可能是我的数据问题吗，因为example data 是没有问题的，我用了日本晴NIP基因组来运行也没有问题，但是换了个基因组fasta使用，就发生了这样的报错，谢谢你的回答！


她抱着明月
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "simon19891216/CentIER" ***@***.***&gt;;
发送时间:&nbsp;2024年8月30日(星期五) 中午1:58
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [simon19891216/CentIER] NameError: name 'st_range' is not defined (Issue #7)





This bug does not affect the prediction of centromere range. In addition, the bug has been fixed. Please download the new version and try again.



At 2024-08-29 17:42:27, "GooLey1025" ***@***.***&gt; wrote:

Traceback (most recent call last):
File "./centIER.py", line 1080, in
else:s1,e1,seq1=st_range[ID]
NameError: name 'st_range' is not defined. Did you mean: 'seq_range'?

Hi, I have encountered the same problem , I would appreciate it for your any reply

**Comment by GooLey1025** [comment]
这是500多M的fa文件，麻烦了！



她抱着明月
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "simon19891216/CentIER"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年9月3日(星期二) 上午8:44
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [simon19891216/CentIER] NameError: name 'st_range' is not defined (Issue #7)





 ***@***.***）联系，我需要看一下您的数据
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 At 2024-09-02 14:14:16, "GooLey1025" ***@***.***&gt; wrote:
 
 ****************************** Start defining the centromere range... *************************
 ****************************** Centromere range determination completed *************************
 ****************************** Annotating the centromere *************************
 Traceback (most recent call last):
 &amp;nbsp; File "/public/home/cszx_huangxh/qiujie/collabrators/gulei/cen_analysis/results/Zlat_genome/./centIER.py", line 1081, in <module&amp;gt;
 &amp;nbsp;&amp;nbsp;&amp;nbsp; else:s1,e1,seq1=st_range[ID]
 ValueError: not enough values to unpack (expected 3, got 0)
 
 
 你好！非常感谢您对CentIER软件的开发！
 
 &amp;nbsp; 这是我用更新的代码后运行的结果，仍然有报错。有可能是我的数据问题吗，因为example data 是没有问题的，我用了日本晴NIP基因组来运行也没有问题，但是换了个基因组fasta使用，就发生了这样的报错，谢谢你的回答！
 
 
 她抱着明月
 ***@***.***
 
 
 
 &amp;nbsp;
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------
 发件人: "simon19891216/CentIER" ***@***.***&amp;gt;;
 发送时间:&amp;nbsp;2024年8月30日(星期五) 中午1:58
 ***@***.***&amp;gt;;
 ***@***.******@***.***&amp;gt;;
 主题:&amp;nbsp;Re: [simon19891216/CentIER] NameError: name 'st_range' is not defined (Issue #7)
 
 
 
 
 
 This bug does not affect the prediction of centromere range. In addition, the bug has been fixed. Please download the new version and try again.
 
 
 
 At 2024-08-29 17:42:27, "GooLey1025" ***@***.***&amp;gt; wrote:
 
 Traceback (most recent call last):
 File "./centIER.py", line 1080, in
 else:s1,e1,seq1=st_range[ID]
 NameError: name 'st_range' is not defined. Did you mean: 'seq_range'?
 
 Hi, I have encountered the same problem , I would appreciate it for your any reply
 
 —
 Reply to this email directly, view it on GitHub, or unsubscribe.
 You are receiving this because you commented.Message ID: ***@***.***&amp;gt;
 —
 Reply to this email directly, view it on GitHub, or unsubscribe.
 You are receiving this because you commented.Message ID: ***@***.***&amp;gt;
 
 —
 Reply to this email directly, view it on GitHub, or unsubscribe.
 You are receiving this because you commented.Message ID: ***@***.***&gt; 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you commented.Message ID: ***@***.***&gt;


从QQ邮箱发来的超大附件

Zlat_genome.fa (517.64M, 2024年10月03日 08:59 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?t=exs_ftn_download&k=7538356173f2c7e82a08182a423350184e4c0157560251031b5d0159551e5053545b18590101031a0759045757025104015d0000643d626d5a59413e03560c585b5d1b0705335f&code=685ad3b7

**Comment by simon19891216** [comment]
不要发在github上，这样所有人都能下载你的数据的，邮件给我
















在 2024-09-03 09:14:38，"GooLey1025" ***@***.***> 写道：

这是500多M的fa文件，麻烦了！



她抱着明月
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "simon19891216/CentIER" ***@***.***&gt;;
发送时间:&nbsp;2024年9月3日(星期二) 上午8:44
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [simon19891216/CentIER] NameError: name 'st_range' is not defined (Issue #7)





***@***.***）联系，我需要看一下您的数据
















At 2024-09-02 14:14:16, "GooLey1025" ***@***.***&gt; wrote:

****************************** Start defining the centromere range... *************************
****************************** Centromere range determination completed *************************
****************************** Annotating the centromere *************************
Traceback (most recent call last):
&amp;nbsp; File "/public/home/cszx_huangxh/qiujie/collabrators/gulei/cen_analysis/results/Zlat_genome/./centIER.py", line 1081, in <module&amp;gt;
&amp;nbsp;&amp;nbsp;&amp;nbsp; else:s1,e1,seq1=st_range[ID]
ValueError: not enough values to unpack (expected 3, got 0)


你好！非常感谢您对CentIER软件的开发！

&amp;nbsp; 这是我用更新的代码后运行的结果，仍然有报错。有可能是我的数据问题吗，因为example data 是没有问题的，我用了日本晴NIP基因组来运行也没有问题，但是换了个基因组fasta使用，就发生了这样的报错，谢谢你的回答！


她抱着明月
***@***.***



&amp;nbsp;




------------------&amp;nbsp;原始邮件&amp;nbsp;------------------
发件人: "simon19891216/CentIER" ***@***.***&amp;gt;;
发送时间:&amp;nbsp;2024年8月30日(星期五) 中午1:58
***@***.***&amp;gt;;
***@***.******@***.***&amp;gt;;
主题:&amp;nbsp;Re: [simon19891216/CentIER] NameError: name 'st_range' is not defined (Issue #7)





This bug does not affect the prediction of centromere range. In addition, the bug has been fixed. Please download the new version and try again.



At 2024-08-29 17:42:27, "GooLey1025" ***@***.***&amp;gt; wrote:

Traceback (most recent call last):
File "./centIER.py", line 1080, in
else:s1,e1,seq1=st_range[ID]
NameError: name 'st_range' is not defined. Did you mean: 'seq_range'?

Hi, I have encountered the same problem , I would appreciate it for your any reply

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you commented.Message ID: ***@***.***&amp;gt;
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you commented.Message ID: ***@***.***&amp;gt;

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you commented.Message ID: ***@***.***&gt;
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you commented.Message ID: ***@***.***&gt;


从QQ邮箱发来的超大附件

Zlat_genome.fa (517.64M, 2024年10月03日 08:59 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?t=exs_ftn_download&k=7538356173f2c7e82a08182a423350184e4c0157560251031b5d0159551e5053545b18590101031a0759045757025104015d0000643d626d5a59413e03560c585b5d1b0705335f&code=685ad3b7

**Comment by hcsun1** [comment]
您好，我也遇到了同样的问题，请问该怎么解决呢？谢谢

command：python centIER.py -o OUTPUT --gff F.fa.Rep.gff3 --mul_cents F.fa > run.log 2> err.log
#F.fa.Rep.gff3 ：repeatmasker结果

error：

Searching for tandem repeat sequences
searching for all LTRs of the input genome
****************************** Start defining the centromere range... *************************
****************************** Centromere range determination completed *************************
****************************** Annotating the centromere *************************
Traceback (most recent call last):
  File "/data2/hcsun2-2/software/CentIER/centIER.py", line 1081, in <module>
    else:s1,e1,seq1=st_range[ID]
         ^^^^^^^^^^
ValueError: not enough values to unpack (expected 3, got 0)

**Comment by simon19891216** [comment]
这个问题不影响最后结果，着丝粒范围已经有了。另外，这个bug目前已经解决，我争取周末上传新的版本。在结果文件里，有个range的文件，那个就是预测的范围



在 2024-09-13 09:26:05，"hcsun1" ***@***.***> 写道：

您好，我也遇到了同样的问题，请问该怎么解决呢？谢谢

command：python centIER.py -o OUTPUT --gff F.fa.Rep.gff3 --mul_cents F.fa > run.log 2> err.log
#F.fa.Rep.gff3 ：repeatmasker结果

error：

Searching for tandem repeat sequences
searching for all LTRs of the input genome
****************************** Start defining the centromere range... *************************
****************************** Centromere range determination completed *************************
****************************** Annotating the centromere *************************
Traceback (most recent call last):
File "/data2/hcsun2-2/software/CentIER/centIER.py", line 1081, in
else:s1,e1,seq1=st_range[ID]
^^^^^^^^^^
ValueError: not enough values to unpack (expected 3, got 0)

**Comment by ZJin2021** [comment]
> 这个问题不影响最后结果，着丝粒范围已经有了。另外，这个bug目前已经解决，我争取周末上传新的版本。在结果文件里，有个range的文件，那个就是预测的范围 在 2024-09-13 09:26:05，"hcsun1" ***@***.***> 写道： 您好，我也遇到了同样的问题，请问该怎么解决呢？谢谢 command：python centIER.py -o OUTPUT --gff F.fa.Rep.gff3 --mul_cents F.fa > run.log 2> err.log #F.fa.Rep.gff3 ：repeatmasker结果 error： Searching for tandem repeat sequences searching for all LTRs of the input genome ****************************** Start defining the centromere range... ************************* ****************************** Centromere range determination completed ************************* ****************************** Annotating the centromere ************************* Traceback (most recent call last): File "/data2/hcsun2-2/software/CentIER/centIER.py", line 1081, in else:s1,e1,seq1=st_range[ID] ^^^^^^^^^^ ValueError: not enough values to unpack (expected 3, got 0) — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>

您好，请问什么时候可以上传新版本。现在的版本虽然能获取到range文件，但其他文件不能正常产生。

**Comment by simon19891216** [comment]
争取明天晚上。最近事情很多



在 2024-11-05 15:43:28，"ZJin2021" ***@***.***> 写道：

这个问题不影响最后结果，着丝粒范围已经有了。另外，这个bug目前已经解决，我争取周末上传新的版本。在结果文件里，有个range的文件，那个就是预测的范围 在 2024-09-13 09:26:05，"hcsun1" @.> 写道： 您好，我也遇到了同样的问题，请问该怎么解决呢？谢谢 command：python centIER.py -o OUTPUT --gff F.fa.Rep.gff3 --mul_cents F.fa > run.log 2> err.log #F.fa.Rep.gff3 ：repeatmasker结果 error： Searching for tandem repeat sequences searching for all LTRs of the input genome ****************************** Start defining the centromere range... ************************* ****************************** Centromere range determination completed ************************* ****************************** Annotating the centromere ************************* Traceback (most recent call last): File "/data2/hcsun2-2/software/CentIER/centIER.py", line 1081, in else:s1,e1,seq1=st_range[ID] ^^^^^^^^^^ ValueError: not enough values to unpack (expected 3, got 0) — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.>

您好，请问什么时候可以上传新版本。现在的版本虽然能获取到range文件，但其他文件不能正常产生。

**Comment by YPGG1234** [comment]
Hello, has the new version been released? The issue does not appear to have been fixed and the version does not appear to have been updated

**Comment by kubek78** [comment]
The same error, latest version of CentIER.

**Comment by simon19891216** [comment]
Based on the information provided by the user, I suggest you further verify the genomic sequence issues. Please note that the genomic sequence files should be at the T2T level and non-chromosomal segments need to be removed from the files.



At 2025-06-02 01:13:32, "kubek78" ***@***.***> wrote:

kubek78 left a comment (simon19891216/CentIER#7)

The same error, latest version of CentIER.

**Comment by pna059** [comment]
Same error here 
****************************** Annotating the centromere *************************
Traceback (most recent call last):
  File "/scratch.ssd/pavlan/job_11341546.pbs-m1/CentIER/centIER.py", line 1081, in <module>
    else:s1,e1,seq1=st_range[ID]
         ^^^^^^^^^^
ValueError: not enough values to unpack (expected 3, got 0)
/var/spool/pbs/mom_priv/jobs/11341546.pbs-m1.metacentrum.cz.SC: line 1: $'\342\200\230clean_scratch\342\200\231': command not found
