### ISSUE TITLE
NameError: name 'gff_gene_number' is not defined

### ISSUE THREAD

**Issue by biomichal** [simon19891216/CentIER#8]
Loading sequence file...
Allocating Memory...
Initializing data structures...
Computing TR Model Statistics...
Scanning Sequence 4...Traceback (most recent call last):
  File "/data/CentIERv3.0/CentIERv3.0.py", line 639, in <module>
    if gff:gff_gene_number=ex_gff(gff)
  File "/data/CentIERv3.0/CentIERv3.0.py", line 141, in ex_gff
    gff_gene_number[j]={}
NameError: name 'gff_gene_number' is not defined

**Comment by biomichal** [comment]
Part of my GFF3 format is as the following: 
Chr01   EVM     gene    24350   27088   .       +       .       ID=Chr01.0002
Chr01   EVM     mRNA    24350   27088   .       +       .       ID=Chr01.0002.t;Parent=Chr01.0002
Chr01   EVM     exon    24350   24500   .       +       .       ID=Chr01.0002.t.exon1;Parent=Chr01.0002.t
Chr01   EVM     CDS     24350   24500   .       +       0       ID=Chr01.0002.t.CDS1;Parent=Chr01.0002.t
Chr01   EVM     exon    26458   26526   .       +       .       ID=Chr01.0002.t.exon2;Parent=Chr01.0002.t
Chr01   EVM     CDS     26458   26526   .       +       2       ID=Chr01.0002.t.CDS2;Parent=Chr01.0002.t
Chr01   EVM     exon    26668   26924   .       +       .       ID=Chr01.0002.t.exon3;Parent=Chr01.0002.t
Chr01   EVM     CDS     26668   26924   .       +       2       ID=Chr01.0002.t.CDS3;Parent=Chr01.0002.t
Chr01   EVM     exon    26993   27088   .       +       .       ID=Chr01.0002.t.exon4;Parent=Chr01.0002.t
Chr01   EVM     CDS     26993   27088   .       +       0       ID=Chr01.0002.t.CDS4;Parent=Chr01.0002.t
Chr01   EVM     gene    27289   33317   .       +       .       ID=Chr01.0003
Chr01   EVM     mRNA    27289   33317   .       +       .       ID=Chr01.0003.t;Parent=Chr01.0003
Chr01   EVM     exon    27289   27517   .       +       .       ID=Chr01.0003.t.exon1;Parent=Chr01.0003.t
Chr01   EVM     CDS     27289   27517   .       +       0       ID=Chr01.0003.t.CDS1;Parent=Chr01.0003.t
Chr01   EVM     exon    31477   31526   .       +       .       ID=Chr01.0003.t.exon2;Parent=Chr01.0003.t
Chr01   EVM     CDS     31477   31526   .       +       2       ID=Chr01.0003.t.CDS2;Parent=Chr01.0003.t
Chr01   EVM     exon    31639   31718   .       +       .       ID=Chr01.0003.t.exon3;Parent=Chr01.0003.t
Chr01   EVM     CDS     31639   31718   .       +       0       ID=Chr01.0003.t.CDS3;Parent=Chr01.0003.t
Chr01   EVM     exon    31947   32393   .       +       .       ID=Chr01.0003.t.exon4;Parent=Chr01.0003.t
Chr01   EVM     CDS     31947   32393   .       +       1       ID=Chr01.0003.t.CDS4;Parent=Chr01.0003.t
Chr01   EVM     exon    33014   33317   .       +       .       ID=Chr01.0003.t.exon5;Parent=Chr01.0003.t
Chr01   EVM     CDS     33014   33317   .       +       1       ID=Chr01.0003.t.CDS5;Parent=Chr01.0003.t
Chr01   EVM     gene    39620   40213   .       -       .       ID=Chr01.0004
Chr01   EVM     mRNA    39620   40213   .       -       .       ID=Chr01.0004.t;Parent=Chr01.0004
Chr01   EVM     exon    39620   40213   .       -       .       ID=Chr01.0004.t.exon1;Parent=Chr01.0004.t
Chr01   EVM     CDS     39620   40213   .       -       0       ID=Chr01.0004.t.CDS1;Parent=Chr01.0004.t
Chr01   EVM     gene    42001   44436   .       -       .       ID=Chr01.0005
Chr01   EVM     mRNA    42001   44436   .       -       .       ID=Chr01.0005.t;Parent=Chr01.0005
Chr01   EVM     exon    44339   44436   .       -       .       ID=Chr01.0005.t.exon1;Parent=Chr01.0005.t
Chr01   EVM     CDS     44339   44436   .       -       0       ID=Chr01.0005.t.CDS1;Parent=Chr01.0005.t
Chr01   EVM     exon    43157   43216   .       -       .       ID=Chr01.0005.t.exon2;Parent=Chr01.0005.t
Chr01   EVM     CDS     43157   43216   .       -       1       ID=Chr01.0005.t.CDS2;Parent=Chr01.0005.t
Chr01   EVM     exon    42431   42597   .       -       .       ID=Chr01.0005.t.exon3;Parent=Chr01.0005.t
Chr01   EVM     CDS     42431   42597   .       -       1       ID=Chr01.0005.t.CDS3;Parent=Chr01.0005.t
Chr01   EVM     exon    42001   42224   .       -       .       ID=Chr01.0005.t.exon4;Parent=Chr01.0005.t
Chr01   EVM     CDS     42001   42224   .       -       2       ID=Chr01.0005.t.CDS4;Parent=Chr01.0005.t

**Comment by biomichal** [comment]
Part of the format form my gff3 file:
![2024-08-18_083953](https://github.com/user-attachments/assets/ccb24a47-f721-4c40-b75d-42dabffeba12)
